name: Build Skia for Android and macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # build-android:
  #   name: Build Skia for Android
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Bazel
  #       uses: bazelbuild/setup-bazelisk@v1
  #     - name: Build Skia for Android
  #       run: bazel build //:skia_public --config=android_arm64 --toolchain=//:ndk_linux_arm64_toolchain_config

  build-macos:
    name: Build Skia for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up deptool
        run: |
          git config --global init.defaultBranch main
          git clone 'https://chromium.googlesource.com/chromium/tools/depot_tools.git'
          export PATH=${PWD}/depot_tools:${PATH}
          python3 tools/git-sync-deps
          bin/fetch-ninja
          export BUILD_ARGS=\
            target_cpu="arm64" \
            is_official_build=true \
            is_debug=false \
            skia_use_libwebp_decode=true \
            skia_use_libwebp_encode=true \
            skia_use_libwebp=false \
            skia_use_system_libjpeg_turbo=false \
            skia_use_system_libpng=false \
            skia_use_system_libwebp=false
          bin/gn gen out/release-darwin-arm64 --args='$BUILD_ARGS'
          bin/gn args out/release-darwin-arm64 --list
          ninja -C out/release-darwin-arm64
          ls -lh out/release-darwin-arm64
